services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: habit_tracker
      POSTGRES_USER: habit_user
      POSTGRES_PASSWORD: habit_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - habit_net

  redis:
    image: redis:7-alpine
    networks:
      - habit_net

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://habit_user:habit_pass@db:5432/habit_tracker
      - REDIS_URL=redis://redis:6379/0
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    depends_on:
      - db
      - redis
    networks:
      - habit_net

  celery:
    build: .
    command: celery -A habit_tracker worker --loglevel=info --pool=solo
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://habit_user:habit_pass@db:5432/habit_tracker
      - REDIS_URL=redis://redis:6379/0
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    depends_on:
      - db
      - redis
    networks:
      - habit_net

  beat:
    build: .
    command: celery -A habit_tracker beat --loglevel=info
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://habit_user:habit_pass@db:5432/habit_tracker
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - habit_net

volumes:
  postgres_data:

networks:
  habit_net:
    driver: bridge