# Generated by Django 6.0.2 on 2026-02-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="telegram_chat_id",
            field=models.BigIntegerField(
                default=0,
                help_text="ID чата для отправки уведомлений",
                verbose_name="Telegram Chat ID",
            ),
            preserve_default=False,
        ),
    ]
