# Generated by Django 5.2.11 on 2026-02-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_habit_telegram_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
